services:
  homepage:
    image: ghcr.io/gethomepage/homepage:latest
    ports:
      - 3000:3000
      # - 9000:9000
      - 9443:9443
    volumes:
      - ./config:/app/config:z
      - /var/run/docker.sock:/var/run/docker.sock
    restart: unless-stopped
    environment:
      - HOMEPAGE_ALLOWED_HOSTS=100.114.98.51:3000
      - PORTAINER_TOKEN=${PORTAINER_TOKEN}
